spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hareram
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  cache:
    cache-names:
    - Student
    redis:
      key-prefix: test
